language: php

php:
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/codecept run

matrix:
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache